----- MODULE ManyAssumes -----
CONSTANTS a, b, c, d
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1
ASSUME a = 1 /\ b = 1 /\ c = 1 /\ d = 1




==========